worker_processes auto;

events {
    worker_connections 4096;
}

http {
    access_log off;
    error_log /dev/stderr error;

    upstream bench_upstream {
        server upstream:8080;
        keepalive 256;
    }

    server {
        listen 8080;

        location / {
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_pass http://bench_upstream;
        }
    }
}
